server:
  undertow:
    io: 2
    worker: 16
    buffer-size: 1024 #以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理 每块buffer的空间大小,越小的空间被利用越充分，不要设置太大，以免影响其他应用，合适即可
    # buffers-per-region: 1024 #每个区分配的buffer数量 , 所以pool的大小是buffer-size * buffers-per-region
    direct-buffers: true #是否分配的直接内存(NIO直接分配的堆外内存)

spring:
  profiles:
    active: @profiles.active@
  application:
    name: @spring.application.name@ #指定服务名称,即服务ID
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      maxFileSize: 5MB
      maxRequestSize: 10MB
